FROM node:10

RUN apt update && apt install -y python build-essential && \
    rm -rf /var/cache/apt/*

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./
RUN yarn install
COPY . /usr/src/app
RUN yarn build
