version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:12

    working_directory: ~/code

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            yarn install

      - run:
          name: run tests
          command: |
            yarn run test-with-coverage

  deploy_staging:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_STAGING.git master

  deploy_production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_PRODUCTION.git master

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - backend:
          filters:
            tags:
              only: /.*/
      - deploy_staging:
          requires:
            - backend
          filters:
            branches:
              only:
                - master
      - deploy_production:
          requires:
            - backend
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*
