name: CI

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn install

    - run: yarn test-with-coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: TnpBot
        text: Fabric Node Proxy
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  deploy_staging:
    runs-on: ubuntu-latest

    if: success() && github.ref == 'refs/heads/master'

    needs: test

    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git origin/master:master
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: dev-watchdog
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/tnpbot.png?size=48
        SLACK_MESSAGE: 'Deploy Staging Success! :parrot:'
        SLACK_TITLE: Fabric Node Proxy
        SLACK_USERNAME: TNPBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
