name: CI

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn install

    - run: yarn test-with-coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: TnpBot
        text: Fabric Node Proxy
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
