name: CI

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install, test and coverage
      uses: actions/tnp-frontend-testing-action@0.1
