name: deploy_staging

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: yarn install
    - run: yarn test-with-coverage

  deploy_staging:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git origin/master:master
